import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, company, phone, message, type = "contact", sourcingInterest } = body;

    console.log("----------------------------------------");
    console.log(`[Form Submission Recieved - Type: ${type.toUpperCase()}]`);
    console.log(`Name: ${name || "N/A"}`);
    console.log(`Email: ${email}`);
    console.log(`Company: ${company || "N/A"}`);
    console.log(`Phone: ${phone || "N/A"}`);
    console.log(`Sourcing Interest: ${sourcingInterest || "N/A"}`);
    console.log(`Message: ${message || "N/A"}`);
    console.log("----------------------------------------");

    // Recipient email
    const recipientEmail = "bhuban@chand.co.in";

    // Build standard email HTML template
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; rounded: 12px; background-color: #fcfdfb;">
        <div style="background-color: #0B3D2E; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #ffffff; margin: 0; font-size: 20px;">SourceTrace Form Submission</h2>
          <span style="color: #53D769; font-size: 12px; font-weight: bold; text-transform: uppercase;">Type: ${type.toUpperCase()}</span>
        </div>
        
        <div style="padding: 20px; color: #334155;">
          <p style="font-size: 16px; margin-top: 0;">Hello,</p>
          <p style="font-size: 14px;">A new form submission was recorded on the SourceTrace website. Details are listed below:</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr style="border-bottom: 1px solid #f1f5f9;">
              <td style="padding: 10px 0; font-weight: bold; font-size: 13px; color: #64748b; width: 140px;">Name:</td>
              <td style="padding: 10px 0; font-size: 14px; color: #0f172a;">${name || "N/A"}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f1f5f9;">
              <td style="padding: 10px 0; font-weight: bold; font-size: 13px; color: #64748b;">Email:</td>
              <td style="padding: 10px 0; font-size: 14px; color: #0f172a;"><a href="mailto:${email}" style="color: #1F7A53; text-decoration: none;">${email}</a></td>
            </tr>
            <tr style="border-bottom: 1px solid #f1f5f9;">
              <td style="padding: 10px 0; font-weight: bold; font-size: 13px; color: #64748b;">Company:</td>
              <td style="padding: 10px 0; font-size: 14px; color: #0f172a;">${company || "N/A"}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f1f5f9;">
              <td style="padding: 10px 0; font-weight: bold; font-size: 13px; color: #64748b;">Phone:</td>
              <td style="padding: 10px 0; font-size: 14px; color: #0f172a;">${phone || "N/A"}</td>
            </tr>
            ${sourcingInterest ? `
            <tr style="border-bottom: 1px solid #f1f5f9;">
              <td style="padding: 10px 0; font-weight: bold; font-size: 13px; color: #64748b;">Sourcing Interest:</td>
              <td style="padding: 10px 0; font-size: 14px; color: #0f172a;">${sourcingInterest}</td>
            </tr>
            ` : ""}
          </table>

          ${message ? `
            <div style="background-color: #f8fafc; border-left: 4px solid #1F7A53; padding: 15px; border-radius: 4px; margin-top: 15px;">
              <span style="font-size: 11px; font-weight: bold; color: #64748b; text-transform: uppercase; display: block; margin-bottom: 5px;">Inquiry / Message</span>
              <p style="margin: 0; font-size: 13px; line-height: 1.5; color: #334155;">${message}</p>
            </div>
          ` : ""}
        </div>
        
        <div style="background-color: #f1f5f9; padding: 15px; text-align: center; border-radius: 0 0 8px 8px; font-size: 11px; color: #94a3b8;">
          This message was auto-generated by the SourceTrace Website Notification Engine.
        </div>
      </div>
    `;

    // Retrieve environment SMTP credentials
    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = process.env.SMTP_PORT ? parseInt(process.env.SMTP_PORT) : 587;
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;

    let transporter;

    if (smtpHost && smtpUser && smtpPass) {
      console.log(`[Email Transporter] Initializing SMTP connection to ${smtpHost}:${smtpPort}...`);
      transporter = nodemailer.createTransport({
        host: smtpHost,
        port: smtpPort,
        secure: smtpPort === 465,
        auth: {
          user: smtpUser,
          pass: smtpPass,
        },
      });
    } else {
      console.log("[Email Transporter] No SMTP credentials configured. Creating Ethereal Test Account...");
      // Create Ethereal test account for dev/testing environment
      const testAccount = await nodemailer.createTestAccount();
      console.log(`[Email Transporter] Ethereal Account Created: user=${testAccount.user}`);
      
      transporter = nodemailer.createTransport({
        host: "smtp.ethereal.email",
        port: 587,
        secure: false,
        auth: {
          user: testAccount.user,
          pass: testAccount.pass,
        },
      });
    }

    // Send mail
    const info = await transporter.sendMail({
      from: smtpUser ? `"SourceTrace Sourcing" <${smtpUser}>` : '"SourceTrace Dev Notification" <no-reply@sourcetrace.com>',
      to: recipientEmail,
      subject: `[SourceTrace Alert] New ${type.charAt(0).toUpperCase() + type.slice(1)} Inquiry from ${company || name || email}`,
      html: emailHtml,
    });

    console.log(`[Email Transporter] Mail sent successfully! MessageID: ${info.messageId}`);
    
    // Ethereal preview link
    const previewUrl = nodemailer.getTestMessageUrl(info);
    if (previewUrl) {
      console.log(`----------------------------------------`);
      console.log(`[DEV TEST LINK] Email Preview Available At:`);
      console.log(`${previewUrl}`);
      console.log(`----------------------------------------`);
    }

    return NextResponse.json({ success: true, previewUrl });
  } catch (error: any) {
    console.error("[Email Transporter Error]", error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
