import { CropPageLayout, CropData } from "@/components/crop-page-layout";

const pageData: CropData = {
  cropKey: "cocoa",
  title: "The Compliance Challenge",
  logline: "Guaranteed  Integrity:  Forest  Protection  and  Payout  Transparency.",
  description: "The camera looks down from above a West African rainforest canopy. The screen displays glowing green farm polygons mapped across the landscape, showing protected areas.",
  colors: {
    primary: "#0F2C1D",
    accent: "#3D1E12",
    accentHex: "#3D1E12",
    bgHex: "#0F2C1D",
    textHex: "#E9B44C"
  },
  scenes: [
  {
    "title": "The Compliance Challenge",
    "description": "The camera descends below the canopy. Text overlays outline challenges such as illegal forest clearing and child labor risks.",
    "visualType": "ledger",
    "interactiveTitle": "Compliance Risk Overlays",
    "parameters": [
      {
        "name": "Child Labor Risk",
        "value": "Low"
      },
      {
        "name": "Deforestation Warning",
        "value": "None"
      }
    ]
  },
  {
    "title": "Deforestation Mapping",
    "description": "The screen shows a farm boundary map generated by a field agent. The system highlights how automatic checks flag any plots that cross into national parks.",
    "visualType": "map",
    "interactiveTitle": "Geographical Park-Boundary Check",
    "parameters": []
  },
  {
    "title": "The Cargill Case Study Model",
    "description": "The user scrolls through a horizontal sequence detailing bag-weighing, tag scanning, and digital payments.",
    "visualType": "scale",
    "interactiveTitle": "Cargill Scale Weight Intake",
    "parameters": []
  },
  {
    "title": "The Certified Shipment",
    "description": "The section displays a digital compliance check showing that the batch meets UTZ and Rainforest Alliance standards. 10 Dynamic Interactive Animations",
    "visualType": "calculator",
    "interactiveTitle": "Verified Premium payment ledger",
    "parameters": []
  }
],
  stats: [
  {
    "label": "Cocoa Smallholders",
    "value": "35,200+"
  },
  {
    "label": "Protected Forest Mapped",
    "value": "48,000 ha"
  },
  {
    "label": "Intake Transformed",
    "value": "100% Deforestation-Free"
  }
],
  imagePath: "/images/crops/cocoa_pods.png",
  diagram: `------------  (Deforestation  Analysis)  ------------+  
           
|
                                                            
|
 
           
v
                                                            
v
 
+---------------------+
     
(Field
 
Validation)
     
+----------------------------------+
 
|
 
Farm
 
Polygon
 
Map
    
|
 
------------------------->
 
|
 
Internal
 
Control
 
System
 
(ICS)
    
|
 
|
 
(GPS
 
Coordinates)
   
|
                            
|
 
(UTZ
 
/
 
Rainforest
 
Certification)
  
|
 
+---------------------+
                            
+----------------------------------+
 
           
|
                                                            
^
 
           
v
                                                            
|
 
+---------------------+
     
(Instant
 
Payment)
      
+----------------------------------+
 
|
 
Digital
 
Scale
 
Tag
   
|
 
------------------------->
 
|
 
Traceable
 
Cocoa
 
Batch
            
|
 
|
 
(Zero-Leakage
 
Weigh)|
                            
|
 
(Cargill
 
Case
 
Study
 
Standard)
    
|
 
+---------------------+
                            
+----------------------------------+
 
 
Cocoa  Cooperatives  Compliance  Indicators  
 Compliance  Directive  
Verification  Engine  Captured  Field  Attribute  
Platform  Output  
Anti-Deforestation  
Landsat  Satellite  Polygons  
 4  
GPS  crop  area  boundaries  
 9  
Automatic  warning  for  plots  breaching  park  lines  
 11  
Child  Labor  Prevention  
M&E  Dynamic  Surveys  
 11  
Community  school  enrollment  logs  
 11  
Real-time  social  risk  audit  maps  
 9  

--- Page 10 ---
Fair  Trade  Premium  
Digital  Wallet  Integration  
 11  
Weigh  scale  volume  data  
 8  
Verified  premium  payment  ledger  
 9  
Organic  Integrity  Internal  Control  System  
 11  
Chemical  input  application  logs  
 9  
Organic  certificate  compliance  reports  8`
};

export default function CocoaSolutionsPage() {
  return <CropPageLayout data={pageData} />;
}
